## Attempts at deploying with gcloud

##Standard ENV
runtime: python38
env: standard

entrypoint: gunicorn -b :$PORT streamlit run app.py
# Manual instancing, B8
instance_class: B8

basic_scaling:
  max_instances: 11
  idle_timeout: 10m
