##Standard ENV
runtime: python38
env: standard

entrypoint: gunicorn -b :$PORT streamlit run:app
# Manual instancing, B8
instance_class: B8

basic_scaling:
  max_instances: 11
  idle_timeout: 10m



## F-Instances, auto scaling
# instance_class: F4_1G

# automatic_scaling:
#   target_cpu_utilization: 0.5
#   min_instances: 5
#   max_instances: 100
#   min_pending_latency: 30ms
#   max_pending_latency: automatic
#   max_concurrent_requests: 50

#Flex
# runtime: python
# env: flex
# entrypoint: gunicorn -b :$PORT main:app
# runtime_config:
#     python_version: 3

# resources:
#   cpu: 4
#   memory_gb: 4
#   disk_size_gb: 10
#   volumes:
#   - name: ramdisk1
#     volume_type: tmpfs
#     size_gb: 1.0

